version: "3.4"
services:
    influxdb_1x:
        image: influxdb:1.8
        environment:
            INFLUXDB_DB: hulajpole
            INFLUXDB_ADMIN_USER: bakunin
            INFLUXDB_ADMIN_PASSWORD: bakunin
        ports:
            - 8086:8086

    infracheck:
        image: quay.io/riotkit/infracheck:v2.0-x86_64
        volumes:
            - ./container-files/infracheck:/data
        ports:
            - 8000:8000
