name: "Release pipeline"
on:
    push:
    create:
        tags:
            - v*

jobs:
    release_docker:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: "Login to quay"
              uses: docker/login-action@v1
              with:
                  registry: quay.io
                  username: ${{ secrets.QUAY_USERNAME }}
                  password: ${{ secrets.QUAY_PASSWORD }}

            - name: "Install build dependencies"
              run: "sudo pip install -r ./requirements.txt"

            - name: "Build and publish docker"
              run: "rkd :release:docker ${GITHUB_REF##*/}"
